### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by eson88866** [h2xlab/CaT#3]
Excuse me

How to solve the following errors during environment installation?

```
# install remaining dependencies
pip install -r requirements.txt
```
```
ERROR: Could not find a version that satisfies the requirement carla==0.9.10 (from versions: 0.9.5, 0.9.12, 0.9.13, 0.9.14)
ERROR: No matching distribution found for carla==0.9.10
```
If I download other carla and its corresponding pythonAPI version, it seems to be unsuccessful

**Comment by Reezzz702** [comment]
Hi, though I'm not the owner of this repo, but I installed carla 0.9.10 with setup_carla.sh from [transfuser repo](https://github.com/autonomousvision/transfuser) then removed carla==0.9.10 in requirements.txt and added
omegaconf==2.2.3
gym==0.17.2
h5py==3.7.0
then run the remaining steps and it works for me. Hopes this can help you.

**Comment by eson88866** [comment]
> Hi, though I'm not the owner of this repo, but I installed carla 0.9.10 with setup_carla.sh from [transfuser repo](https://github.com/autonomousvision/transfuser) then removed carla==0.9.10 in requirements.txt and added omegaconf==2.2.3 gym==0.17.2 h5py==3.7.0 then run the remaining steps and it works for me. Hopes this can help you.

Thank you for your help
But after I execute bash ./leaderboard/scripts/local_evaluation.sh
Other problems have arisen as follows
```
leaderboard/leaderboard/leaderboard_evaluator_local.py:24: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
leaderboard/leaderboard/leaderboard_evaluator_local.py:113: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):

========= Preparing RouteScenario_1 (repetition 0) =========
> Setting up the agent
weights/teacher_model.th
longest6_08_23_16_25_34
> Loading the world
No more spawn points to use. Spawned 256 actors out of 500
> Running the route
======[Agent] Wallclock_time = 2023-08-23 16:25:37.623652 / 0.0 / Sim_time = 0.05000000074505806 / 50.00000074505806x
Sparse Waypoints: 32
Dense Waypoints: 1098
Map:  Town01
obs_configs:  {'module': 'birdview.chauffeurnet', 'width_in_pixels': 320, 'pixels_ev_to_bottom': 40, 'pixels_per_meter': 5.0, 'history_idx': [-16, -11, -6, -1], 'extrapolation_seconds': 2, 'future_idx': [21, 16, 11, 6, 1], 'scale_bbox': True, 'scale_mask_col': 1.0}

Stopping the route, the agent has crashed:
> OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type


Traceback (most recent call last):
  File "/home/t2-503/GuanYan/CaT/leaderboard/leaderboard/scenarios/scenario_manager_local.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/t2-503/GuanYan/CaT/leaderboard/leaderboard/autoagents/agent_wrapper_local.py", line 81, in __call__
    return self._agent()
  File "/home/t2-503/GuanYan/CaT/leaderboard/leaderboard/autoagents/autonomous_agent_local.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "/home/t2-503/anaconda3/envs/cat-env1/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/t2-503/GuanYan/CaT/team_code/teacher_agent.py", line 293, in run_step
    tick_data = self.tick(input_data)
  File "/home/t2-503/GuanYan/CaT/team_code/teacher_agent.py", line 218, in tick
    chauffeur = self.bev_manager.get_observation(self.hazard_source)
  File "/home/t2-503/GuanYan/CaT/cat/birdview/chauffeurnet.py", line 192, in get_observation
    = self._get_history_masks(M_warp)
  File "/home/t2-503/GuanYan/CaT/cat/birdview/chauffeurnet.py", line 399, in _get_history_masks
    tl_green_masks.append(self._get_mask_from_stopline_vtx(tl_green, M_warp))
  File "/home/t2-503/GuanYan/CaT/cat/birdview/chauffeurnet.py", line 417, in _get_mask_from_stopline_vtx
    cv.line(mask, tuple(stopline_warped[0, 0]), tuple(stopline_warped[1, 0]),
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator_local.py", line 375, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/t2-503/GuanYan/CaT/leaderboard/leaderboard/scenarios/scenario_manager_local.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/t2-503/GuanYan/CaT/leaderboard/leaderboard/scenarios/scenario_manager_local.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper_local.AgentError: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
```
May I ask if you have encountered similar problems and how to solve them ?

**Comment by Reezzz702** [comment]
I saw this bug too, it seems to be that it pass stop_line_warped into the function directly which is a float number, however cv2.line() only accept int type. So I cast it to int and it solve the problem.

**Comment by eson88866** [comment]
> I saw this bug too, it seems to be that it pass stop_line_warped into the function directly which is a float number, however cv2.line() only accept int type. So I cast it to int and it solve the problem.

Thank you very much for your help

**Comment by Reezzz702** [comment]
> > I saw this bug too, it seems to be that it pass stop_line_warped into the function directly which is a float number, however cv2.line() only accept int type. So I cast it to int and it solve the problem.
> 
> Thank you very much for your help

May I ask if you encountered the problem mentioned in [issue](https://github.com/h2xlab/CaT/issues/4) I post during the evaluation?

**Comment by eson88866** [comment]
> May I ask if you encountered the problem mentioned in [issue](https://github.com/h2xlab/CaT/issues/4) I post during the evaluation?

For teacher, I ran two evaluations and found the other actors would get stuck in traffic, causing teacher to get blocked at the same intersection. Is this what you are asking about?
For students, I also did not find checkpoint.

**Comment by Reezzz702** [comment]
> For teacher, I ran two evaluations and found the other actors would get stuck in traffic, causing teacher to get blocked at the same intersection. Is this what you are asking about? For students, I also did not find checkpoint.

No, I mean that there are total 36 routes in the evaluation to run. In my case, it run normally in the first 12(0~11) routes without any crash of Carla simulator, however, whenever it start to run route 12, Carla crash with a segmentation fault error message. I know that Carla is easily to crash during simulation, but in my experience, it should be randomly occur rather than in this kind of certain pattern, it make me very confused.
